modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/LCLPYT/ServerBaseForge/issues"
displayURL="https://github.com/LCLPYT/ServerBaseForge"
authors="LCLP"
license="MIT"

[[mods]]
    modId="serverbase"
    version="${version}"
    displayName="ServerBase"
    updateJSONURL="https://raw.githubusercontent.com/LCLPYT/ServerBaseForge/master/ServerBase/update.json"
    logoFile="logo.png"
    credits="LCLPNetwork!"
    description='''
    Internal Server mod.
    '''
    
    [[dependencies.serverbase]]
        modId="corebase"
        mandatory=true
        versionRange="[1.4,)"
        ordering="BEFORE"
        side="SERVER"
    [[dependencies.serverbase]]
        modId="core"
        mandatory=true
        versionRange="[1.3,)"
        ordering="BEFORE"
        side="SERVER"
    [[dependencies.serverbase]]
        modId="forge"
        mandatory=true
        versionRange="[34,)"
        ordering="NONE"
        side="SERVER"
    [[dependencies.serverbase]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.3]"
        ordering="NONE"
        side="BOTH"
